export const aiAssets = [
  {
    name: "AIFI Reasoning Model",
    symbol: "AIMR",
    provider: "Coolha Labs",
    category: "Reasoning API",
    version: "v1.4",
    context: "128K",
    capability: "Agent planning, code review, structured research",
    apiPrice: "$0.42 / 1K calls",
    availability: "99.95%",
    latency: "820 ms p50",
    throughput: "4,800 RPM",
    billing: "USDC / USDT",
    access: "API key after wallet authorization",
  },
  {
    name: "Vision Index Model",
    symbol: "VIXM",
    provider: "Open Vision DAO",
    category: "Vision API",
    version: "v2.1",
    context: "32K",
    capability: "Image understanding, document extraction, visual QA",
    apiPrice: "$0.31 / 1K calls",
    availability: "99.9%",
    latency: "1.1 s p50",
    throughput: "2,200 RPM",
    billing: "USDC / USDT",
    access: "API key after wallet authorization",
  },
  {
    name: "Trading Agent Model",
    symbol: "TRAG",
    provider: "Quant Node",
    category: "Market API",
    version: "v0.9",
    context: "64K",
    capability: "Market monitoring, strategy simulation, risk alerts",
    apiPrice: "$0.65 / 1K calls",
    availability: "99.7%",
    latency: "940 ms p50",
    throughput: "1,600 RPM",
    billing: "USDC / USDT",
    access: "API key after wallet authorization",
  },
]

export const agentServices = [
  {
    name: "Research Analyst Agent",
    category: "Research",
    provider: "Coolha Agent Network",
    service: "Market research, source review, memo generation",
    settlement: "x402 programmable payment",
    identity: "ERC-8004 compatible on-chain identity",
    trust: "Verifiable history and reputation records",
  },
  {
    name: "Treasury Operations Agent",
    category: "Operations",
    provider: "Ops Node",
    service: "Stablecoin payment checks, invoice matching, treasury alerts",
    settlement: "Pay per completed task",
    identity: "Wallet-owned agent profile",
    trust: "Auditable task history",
  },
  {
    name: "Portfolio Monitor Agent",
    category: "Portfolio",
    provider: "Signal Desk",
    service: "Watchlists, risk alerts, RWA document reminders",
    settlement: "Subscription or task-based payment",
    identity: "On-chain service endpoint",
    trust: "Public service record",
  },
]

export const rwaAssets = [
  {
    name: "US Treasury Fund",
    symbol: "USTF",
    type: "Treasury",
    issuer: "Regulated Issuer Required",
    jurisdiction: "United States",
    underlying: "Short-term US Treasury exposure",
    nav: "$100.24",
    distribution: "Variable distribution, not guaranteed",
    maturity: "Rolling 0-12 month",
    totalValue: "$84.2M",
    availableSupply: "216,000 USTF",
    blockchain: "Base",
    eligibility: "KYC and whitelist required",
    risk: "Rates, issuer, custody, liquidity, transfer restrictions",
  },
  {
    name: "Tokenized Private Credit",
    symbol: "TPC",
    type: "Private Credit",
    issuer: "Issuer Disclosure Required",
    jurisdiction: "Singapore",
    underlying: "Senior secured private credit pool",
    nav: "$50.18",
    distribution: "Depends on pool performance",
    maturity: "36 months",
    totalValue: "$31.5M",
    availableSupply: "88,400 TPC",
    blockchain: "Polygon",
    eligibility: "Approved investors only",
    risk: "Credit, default, valuation, redemption gates",
  },
  {
    name: "Real Estate Income Token",
    symbol: "REITX",
    type: "Real Estate",
    issuer: "Property SPV Required",
    jurisdiction: "United Kingdom",
    underlying: "Commercial property income rights",
    nav: "$24.72",
    distribution: "Subject to rent collection and expenses",
    maturity: "Open-ended",
    totalValue: "$19.7M",
    availableSupply: "142,500 REITX",
    blockchain: "Ethereum",
    eligibility: "Jurisdiction and transfer checks required",
    risk: "Property, vacancy, valuation, legal structure",
  },
]

export const portfolioPositions = [
  { asset: "USDC", type: "Stablecoin", balance: "10,000", price: "$1.00", value: "$10,000" },
  { asset: "API Credits", type: "AI Compute", balance: "25,000 calls", price: "$0.42 / 1K", value: "$10.50" },
  { asset: "USTF", type: "RWA Token", balance: "950", price: "$100.24", value: "$95,228" },
]

export const supportedChains = ["Ethereum", "Base", "Polygon", "Arbitrum"]
